// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// coef_boot_cpp
NumericMatrix coef_boot_cpp(NumericMatrix X, NumericVector y, int R, double alpha, int seed, String method);
RcppExport SEXP _alloy_coef_boot_cpp(SEXP XSEXP, SEXP ySEXP, SEXP RSEXP, SEXP alphaSEXP, SEXP seedSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(coef_boot_cpp(X, y, R, alpha, seed, method));
    return rcpp_result_gen;
END_RCPP
}
// rsq_boot_cpp
NumericVector rsq_boot_cpp(NumericMatrix X, NumericVector y, int B, double alpha, bool adjusted, int seed);
RcppExport SEXP _alloy_rsq_boot_cpp(SEXP XSEXP, SEXP ySEXP, SEXP BSEXP, SEXP alphaSEXP, SEXP adjustedSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type adjusted(adjustedSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(rsq_boot_cpp(X, y, B, alpha, adjusted, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_alloy_coef_boot_cpp", (DL_FUNC) &_alloy_coef_boot_cpp, 6},
    {"_alloy_rsq_boot_cpp", (DL_FUNC) &_alloy_rsq_boot_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_alloy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
