# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coef_boot_cpp <- function(X, y, R = 2000L, alpha = 0.05, seed = -1L, method = "perc") {
    .Call(`_alloy_coef_boot_cpp`, X, y, R, alpha, seed, method)
}

rsq_boot_cpp <- function(X, y, B = 1000L, alpha = 0.05, adjusted = TRUE, seed = -1L) {
    .Call(`_alloy_rsq_boot_cpp`, X, y, B, alpha, adjusted, seed)
}

